var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}return globalThis};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Math.hypot",function(a){return a?a:function(a){if(2>arguments.length)return arguments.length?Math.abs(arguments[0]):0;var b,c,e;for(b=e=0;b<arguments.length;b++)e=Math.max(e,Math.abs(arguments[b]));if(1E100<e||1E-100>e){if(!e)return e;for(b=c=0;b<arguments.length;b++){var f=Number(arguments[b])/e;c+=f*f}return Math.sqrt(c)*e}for(b=c=0;b<arguments.length;b++)f=Number(arguments[b]),c+=f*f;return Math.sqrt(c)}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,b,d){var c=this.length||0;0>b&&(b=Math.max(0,c+b));if(null==d||d>c)d=c;d=Number(d);0>d&&(d=Math.max(0,c+d));for(b=Number(b||0);b<d;b++)this[b]=a;return this}},"es6","es3");var canvas=document.querySelector("canvas");canvas.width=window.innerWidth;canvas.height=window.innerHeight;cxt=canvas.getContext("2d");var keys={left:!1,right:!1};
addEventListener("keydown",function(a){switch(a.code){case "ShiftLeft":keys.left=!0;break;case "ShiftRight":keys.right=!0}});addEventListener("keyup",function(a){switch(a.code){case "ShiftLeft":keys.left=!1;break;case "ShiftRight":keys.right=!1}});
var time_survived=0,player={colour:"firebrick",x:window.innerWidth/2,y:500,radius:4,jump_length:10,jump_variation:40,jumped_left:!1,jumped_right:!1,update:function(a){var c=this;!this.jumped_left&&keys.left&&(this.jumped_left=!0,this.x-=this.jump_length+Math.random()*this.jump_variation,ZZFX.z(57087));!this.jumped_right&&keys.right&&(this.jumped_right=!0,this.x+=this.jump_length+Math.random()*this.jump_variation,ZZFX.z(57087));this.jumped_left=this.jumped_left&&keys.left;this.jumped_right=this.jumped_right&&
keys.right;this.x=Math.max(this.radius,Math.min(this.x,canvas.width-this.radius));obstacles.forEach(function(a){Math.hypot(c.x-a.x,c.y-a.y)<=c.radius+a.radius&&(ZZFX.z(21486),end())})},reset:function(){this.x=window.innerWidth/2;this.y=500}},obstacles=[],density=.01,spawn_delay=100,last_spawn=0;function Obstacle(a,c){this.x=a;this.y=0;this.radius=isNaN(c)||5>c?5:c;this.active=!0}Obstacle.prototype.colour="silver";
Obstacle.prototype.speed=function(){return.4+.8/Math.PI*Math.atan(9*(time_survived/6E4-1))};Obstacle.prototype.update=function(a){this.y+=a*this.speed();this.y>canvas.height&&(this.active=!1)};
function draw(){cxt.clearRect(0,0,canvas.width,canvas.height);obstacles.forEach(function(a){cxt.fillStyle=a.colour;cxt.beginPath();cxt.arc(a.x,a.y,a.radius,0,2*Math.PI);cxt.closePath();cxt.fill()});cxt.fillStyle=player.colour;cxt.beginPath();cxt.arc(player.x,player.y,player.radius,0,2*Math.PI);cxt.closePath();cxt.fill()}var last_time=null,lapse=0,max_lapse=100,playing=!1;
function animate(a){lapse=null==last_time?0:a-last_time;last_time=a;lapse>max_lapse&&(lapse=max_lapse);playing&&(time_survived+=lapse,last_spawn+=lapse,last_spawn>spawn_delay&&(last_spawn=0,obstacles.push(new Obstacle(Math.random()*canvas.width,10))),player.update(lapse),obstacles=obstacles.filter(function(a){return a.active}),obstacles.forEach(function(a){a.update(lapse)}),requestAnimationFrame(animate));draw()}
function start(a){"Shift"==a.key&&(document.getElementById("instructions").style.visibility="hidden",playing=!0,requestAnimationFrame(animate),removeEventListener("keyup",start))}
function end(){document.getElementById("instructions").innerHTML="press SHIFT to restart.";document.getElementById("instructions").innerHTML+="<br />score: "+Math.floor(time_survived/1E3);document.getElementById("instructions").style.visibility="visible";playing=!1;cxt.clearRect(0,0,canvas.width,canvas.height);cxt.fillStyle=player.colour;cxt.beginPath();cxt.arc(player.x,player.y,player.radius,0,2*Math.PI);cxt.closePath();cxt.fill();reset();addEventListener("keyup",start)}
function reset(){last_time=null;player.reset();time_survived=last_spawn=0;obstacles=[]}cxt.fillStyle=player.colour;cxt.beginPath();cxt.arc(player.x,player.y,player.radius,0,2*Math.PI);cxt.closePath();cxt.fill();addEventListener("keyup",start);
